deploy:
  needs: build
  runs-on: ubuntu-latest

  steps:
    - name: Deploy to Control Node
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.CONTROL_NODE_IP }}
        username: ubuntu
        key: ${{ secrets.CONTROL_NODE_KEY }}
        script: |

          # Ensure required tools exist
          sudo apt-get update -y
          sudo apt-get install -y git ansible

          # Clone repo first time OR pull latest changes
          if [ ! -d "$HOME/devops-django-demo" ]; then
            git clone https://github.com/${{ github.repository }}.git $HOME/devops-django-demo
          fi

          cd $HOME/devops-django-demo
          git pull origin main

          # Install required Ansible collection (needed for docker modules)
          ansible-galaxy collection install community.docker

          # Run deployment
          ansible-playbook -i ansible/inventory.ini ansible/deploy.yml